# Generated by Django 3.2.3 on 2021-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('genesis', 'genesis'), ('exodus', 'exodus'), ('leviticus', 'leviticus'), ('numbers', 'numbers'), ('deuteronomy', 'deuteronomy')], max_length=15)),
                ('chapter_no', models.IntegerField()),
                ('line_no', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('translation', models.CharField(default='', max_length=200)),
                ('desc', models.TextField()),
                ('lines', models.ManyToManyField(to='torah.Line')),
            ],
        ),
    ]
