# Generated by Django 2.1.3 on 2018-11-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('genesis', 'genesis'), ('exodus', 'exodus'), ('leviticus', 'leviticus'), ('numbers', 'numbers'), ('deuteronomy', 'deuteronomy')], max_length=15)),
                ('chapter', models.IntegerField()),
                ('line', models.IntegerField()),
            ],
        ),
    ]
