# Generated by Django 2.1.3 on 2018-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torah', '0002_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lines',
            field=models.ManyToManyField(to='torah.Line'),
        ),
    ]
