# Generated by Django 2.1.3 on 2018-11-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torah', '0004_word_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
